In [46]:
from pymongo import MongoClient
import pandas as pd
from flask import Flask, request, jsonify
import requests
from pprint import pprint

In [124]:
base = 'https://www.ncei.noaa.gov/cdo-web/api/v2/locations?startdate=2022-01-01'
token = 'WovxJbmTpTqHSzvOJjcyptMahfCMyDAt'
headers = {'token': token}

response = requests.get(base, headers=headers)
data = response.json()
pprint(data)
if response.ok:
    locations = data['results']
    
    for location in locations:
        if 'US' in location['name']:
            miami_id = location['id']
            print(f"The ID for a location containing 'Miami' is: {miami_id}")
            break
            
    else:
        print("No location was found.")
else:
    print(f"Request failed with status code {response.status_code}.")

{'metadata': {'resultset': {'count': 38616, 'limit': 25, 'offset': 1}},
 'results': [{'datacoverage': 0.9978,
              'id': 'CITY:AE000001',
              'maxdate': '2024-01-21',
              'mindate': '1983-01-02',
              'name': 'Abu Dhabi, AE'},
             {'datacoverage': 1,
              'id': 'CITY:AE000002',
              'maxdate': '2024-01-21',
              'mindate': '1944-03-20',
              'name': 'Ajman, AE'},
             {'datacoverage': 1,
              'id': 'CITY:AE000003',
              'maxdate': '2024-01-21',
              'mindate': '1944-03-20',
              'name': 'Dubai, AE'},
             {'datacoverage': 1,
              'id': 'CITY:AE000006',
              'maxdate': '2024-01-21',
              'mindate': '1944-03-20',
              'name': 'Sharjah, AE'},
             {'datacoverage': 1,
              'id': 'CITY:AG000001',
              'maxdate': '2024-01-21',
              'mindate': '1877-04-07',
              'name': 'Algiers, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000002',
              'maxdate': '2024-01-21',
              'mindate': '1909-11-23',
              'name': 'Annaba, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000003',
              'maxdate': '2024-01-21',
              'mindate': '1973-04-03',
              'name': 'Batna, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000004',
              'maxdate': '2024-01-21',
              'mindate': '1957-01-09',
              'name': 'Bechar, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000005',
              'maxdate': '2024-01-21',
              'mindate': '1909-11-23',
              'name': 'Bejaia, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000006',
              'maxdate': '2024-01-21',
              'mindate': '1880-05-18',
              'name': 'Constantine, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000007',
              'maxdate': '2024-01-21',
              'mindate': '1995-10-25',
              'name': 'Guelma, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000008',
              'maxdate': '2024-01-21',
              'mindate': '1888-01-01',
              'name': 'Laghouat, AG'},
             {'datacoverage': 0.9873,
              'id': 'CITY:AG000009',
              'maxdate': '2024-01-21',
              'mindate': '1995-10-25',
              'name': 'Medea, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000010',
              'maxdate': '2024-01-21',
              'mindate': '1976-04-28',
              'name': 'Mostaganem, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000011',
              'maxdate': '2024-11-14',
              'mindate': '1957-01-01',
              'name': 'Oran, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000012',
              'maxdate': '2024-01-21',
              'mindate': '1985-02-07',
              'name': 'Oum el Bouaghi, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000013',
              'maxdate': '2024-01-21',
              'mindate': '1981-01-01',
              'name': 'Saida, AG'},
             {'datacoverage': 0.9107,
              'id': 'CITY:AG000014',
              'maxdate': '2024-01-21',
              'mindate': '1995-10-25',
              'name': 'Sidi-Bel-Abbes, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000015',
              'maxdate': '2024-01-21',
              'mindate': '1957-12-31',
              'name': 'Skikda, AG'},
             {'datacoverage': 1,
              'id': 'CITY:AG000017',
              'maxdate': '2024-01-21',
              'mindate': '1981-01-01',
              'name': 'Tlemcen, AG'},
             {'datacoverage': 0.7127,
              'id': 'CITY:AL000001',
              'maxdate': '2024-01-21',
              'mindate': '1973-02-05',
              'name': 'Durres, AL'},
             {'datacoverage': 0.9699,
              'id': 'CITY:AL000005',
              'maxdate': '2024-01-21',
              'mindate': '1940-04-01',
              'name': 'Tirana, AL'},
             {'datacoverage': 1,
              'id': 'CITY:AM000001',
              'maxdate': '2024-01-21',
              'mindate': '1885-06-01',
              'name': 'Yerevan, AM'},
             {'datacoverage': 0.4132,
              'id': 'CITY:AO000005',
              'maxdate': '2024-01-21',
              'mindate': '1960-04-01',
              'name': 'Luanda, AO'},
             {'datacoverage': 1,
              'id': 'CITY:AO000006',
              'maxdate': '2024-01-21',
              'mindate': '1957-09-03',
              'name': 'Lubango, AO'}]}
No location was found.

In [135]:
base = 'https://www.ncei.noaa.gov/cdo-web/api/v2/locations?startdate=2020-01-01'
token = 'WovxJbmTpTqHSzvOJjcyptMahfCMyDAt'
headers = {'token': token}

response = requests.get(base, headers=headers)
data = response.json()
locations = data['results']
for location in locations:
    
    print(location)
#         if 'CA' in location['name']:
#             miami_id = location['id']
#             print(f"The ID for a location containing 'Miami' is: {miami_id}")
#             break
# pprint(locations)

{'mindate': '1983-01-02', 'maxdate': '2024-01-21', 'name': 'Abu Dhabi, AE', 'datacoverage': 0.9978, 'id': 'CITY:AE000001'}
{'mindate': '1944-03-20', 'maxdate': '2024-01-21', 'name': 'Ajman, AE', 'datacoverage': 1, 'id': 'CITY:AE000002'}
{'mindate': '1944-03-20', 'maxdate': '2024-01-21', 'name': 'Dubai, AE', 'datacoverage': 1, 'id': 'CITY:AE000003'}
{'mindate': '1944-03-20', 'maxdate': '2024-01-21', 'name': 'Sharjah, AE', 'datacoverage': 1, 'id': 'CITY:AE000006'}
{'mindate': '1966-03-02', 'maxdate': '2021-08-30', 'name': 'Kabul, AF', 'datacoverage': 0.5777, 'id': 'CITY:AF000007'}
{'mindate': '1973-01-02', 'maxdate': '2020-12-31', 'name': 'Kandahar, AF', 'datacoverage': 1, 'id': 'CITY:AF000008'}
{'mindate': '1877-04-07', 'maxdate': '2024-01-21', 'name': 'Algiers, AG', 'datacoverage': 1, 'id': 'CITY:AG000001'}
{'mindate': '1909-11-23', 'maxdate': '2024-01-21', 'name': 'Annaba, AG', 'datacoverage': 1, 'id': 'CITY:AG000002'}
{'mindate': '1973-04-03', 'maxdate': '2024-01-21', 'name': 'Batna, AG', 'datacoverage': 1, 'id': 'CITY:AG000003'}
{'mindate': '1957-01-09', 'maxdate': '2024-01-21', 'name': 'Bechar, AG', 'datacoverage': 1, 'id': 'CITY:AG000004'}
{'mindate': '1909-11-23', 'maxdate': '2024-01-21', 'name': 'Bejaia, AG', 'datacoverage': 1, 'id': 'CITY:AG000005'}
{'mindate': '1880-05-18', 'maxdate': '2024-01-21', 'name': 'Constantine, AG', 'datacoverage': 1, 'id': 'CITY:AG000006'}
{'mindate': '1995-10-25', 'maxdate': '2024-01-21', 'name': 'Guelma, AG', 'datacoverage': 1, 'id': 'CITY:AG000007'}
{'mindate': '1888-01-01', 'maxdate': '2024-01-21', 'name': 'Laghouat, AG', 'datacoverage': 1, 'id': 'CITY:AG000008'}
{'mindate': '1995-10-25', 'maxdate': '2024-01-21', 'name': 'Medea, AG', 'datacoverage': 0.9873, 'id': 'CITY:AG000009'}
{'mindate': '1976-04-28', 'maxdate': '2024-01-21', 'name': 'Mostaganem, AG', 'datacoverage': 1, 'id': 'CITY:AG000010'}
{'mindate': '1957-01-01', 'maxdate': '2024-11-14', 'name': 'Oran, AG', 'datacoverage': 1, 'id': 'CITY:AG000011'}
{'mindate': '1985-02-07', 'maxdate': '2024-01-21', 'name': 'Oum el Bouaghi, AG', 'datacoverage': 1, 'id': 'CITY:AG000012'}
{'mindate': '1981-01-01', 'maxdate': '2024-01-21', 'name': 'Saida, AG', 'datacoverage': 1, 'id': 'CITY:AG000013'}
{'mindate': '1995-10-25', 'maxdate': '2024-01-21', 'name': 'Sidi-Bel-Abbes, AG', 'datacoverage': 0.9995, 'id': 'CITY:AG000014'}
{'mindate': '1957-12-31', 'maxdate': '2024-01-21', 'name': 'Skikda, AG', 'datacoverage': 1, 'id': 'CITY:AG000015'}
{'mindate': '1981-01-01', 'maxdate': '2024-01-21', 'name': 'Tlemcen, AG', 'datacoverage': 1, 'id': 'CITY:AG000017'}
{'mindate': '1973-02-05', 'maxdate': '2024-01-21', 'name': 'Durres, AL', 'datacoverage': 0.9925, 'id': 'CITY:AL000001'}
{'mindate': '1940-04-01', 'maxdate': '2024-01-21', 'name': 'Tirana, AL', 'datacoverage': 0.9925, 'id': 'CITY:AL000005'}
{'mindate': '1885-06-01', 'maxdate': '2024-01-21', 'name': 'Yerevan, AM', 'datacoverage': 1, 'id': 'CITY:AM000001'}